INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Accounting' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Afrikaans' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Ancient History' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Anthropology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied Art and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied Business' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied ICT' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Arabic' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Archaeology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Art and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Bengali' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Biblical Hebrew' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Biology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Business' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Business Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Chemistry' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Chinese' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Citizenship Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Classical Civilisation' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Classical Greek' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Classical Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Communication and Culture' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Computer Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Computing' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Creative Writing' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Critical Thinking' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Dance' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Design and Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Design and Textiles' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Digital Media and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Digital Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Divinity' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Drama' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Drama and Theatre' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Dutch' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Economics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Economics and Business' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Electronics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Engineering' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'English Language' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'English Language and Literature' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'English Literature' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Environmental Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Environmental Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Environmental Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Fashion and Textiles' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Film Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Food Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Food Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'French' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Further Mathematics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'General Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Geography' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Geology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'German' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Global Development' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Global Perspectives and Research' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Government and Politics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Greek' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Gujarati' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Health and Social Care' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Hindi' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Hinduism' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'History' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'History of Art' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Home Economics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Human Biology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Humanities' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'ICT' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Information Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Irish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Islamic Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Italian' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Japanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Journalism' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Latin' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Law' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Leisure Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Life and Health Sciences' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Mathematics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Media Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Modern Hebrew' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Modern Languages' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Moving Image Arts' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Music Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Nutrition and Food Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Panjabi' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Performance Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Performing Arts' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Persian' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Philosophy' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Physical Education' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Physical Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Physics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Polish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Politics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Portuguese' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Product Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Professional Business Services' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Psychology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Pure Mathematics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Quantitative Methods' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Religious Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Russian' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Science in Society' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Sociology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Software Systems Development' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Spanish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Sports Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Statistics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Systems and Control Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Tamil' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Technology and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Thinking Skills' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Travel and Tourism' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Turkish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Urdu' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Welsh' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'World Development' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Afghan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'African' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Albanian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'American' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Arabian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Argentinian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Armenian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Asian Fusion' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Australian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Austrian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Bagels' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Bakery' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Bangladeshi' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Barbeque' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Belgian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Brasseries' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Brazilian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Breakfast' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'British' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Brunch' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Buffets' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Burgers' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Burmese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cafes' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cafeteriafood hamburgers' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cajun' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Californian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Calzones' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cambodian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cantonese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Caribbean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Catalan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cheesesteaks' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chicken' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chicken Wings' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chili' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chinese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Classic' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Coffee and Tea' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Colombian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Comfort Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Costa Rican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Creole' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Crepes' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cuban' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Czech' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Delis' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Dessertindian food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Dim Sum' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Diner' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Dominican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Eclectic' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ecuadorian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Egyptian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'El Salvadoran' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Empanadas' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'English' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ethiopian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fast Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Filipino' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fine Dining' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fish & Chips' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fondue' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Food Cart' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Food Court' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Food Stands' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'French' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fresh Fruits' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Frozen Yogurt' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Gastropubs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'German' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Gluten-Free' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Greek' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Grill' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Guatemalan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Gyro' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Haitian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Halalfood korean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hawaiian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Himalayan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hoagies' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hot Dogs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hot Pot' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hungarian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Iberian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ice Cream' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Indian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Indonesian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Irish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Italian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Jamaican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Japanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Kids' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Korean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Kosher' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Laotian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Late Night' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Latin American' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Lebanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Live or Raw Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Low Carb' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Malaysian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mandarin' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mediterranean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mexican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Middle Eastern' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Modern European' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mongolian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Moroccan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Nepalese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Noodles' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Nouvelle cuisine' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Nutritious' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Organic' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pakistani' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pancakes' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pasta' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Persian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Persian or Iranian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Peruvian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pitas' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pizza' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Polish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Portuguese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Potato' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Poutineries' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pub Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Puerto Rican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ribs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Russian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Salad' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Sandwiches' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Scandinavian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Scottish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Seafood' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Senegalese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Singaporean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Slovakian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Small Plates' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Smoothies and Juices' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Soul Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Soup' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'South African' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'South American' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Southern' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Southwestern' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Spanish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Sri Lankan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Steakhouses' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Subs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Supper Clubs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Sushi Bars' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Syrian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Szechwan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Taiwanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Tapas' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Tex-Mex' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Thai' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Tibetan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Turkish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ukrainian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Uzbek' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Vegan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Vegetarian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Vietnamese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Wraps' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Action-adventure' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Adventuring' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Alternate reality' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Arcade' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Board' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Casual' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Computer' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Console' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Conversation' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Cooperative' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Daring' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Dice' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Drinking' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Educational' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Escape' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'First person shooter' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Flash' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Guessing' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Handheld' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Medieval' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Mini' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Mobile' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Multiplayer' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Multiplayer online battle arena' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Narrative' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Party' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Pencil-and-paper' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Platforming' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Pub' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Puzzles' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Real-time strategy' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Role-playing' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Role-playing video' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Skill' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Strategy' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Street' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Tabletop' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Third person shooter' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Video' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Wedding' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Absurdist or surreal or whimsical' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Action' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Adventure' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Comedy' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Crime' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Drama' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Fantasy' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Historical' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Historical fiction' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Horror' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Magical realism' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Mystery' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Paranoid' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Philosophical' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Political' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Romance' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Saga' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Satire' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Science fiction' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Slice of Life' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Speculative' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Thriller' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Urban' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Western' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Action' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Adventure' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Animation' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Biography' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Comedy' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Crime' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Documentary' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Drama' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Family' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Fantasy' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Film-Noir' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'History' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Horror' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Musical' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Mystery' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Romance' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Sci-Fi' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Sport' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Thriller' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'War' );
INSERT INTO Interest_Subcategory VALUES ( 'Movie', 'Western' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Alternative Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Blues' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Classical Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Country Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Dance Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Easy Listening' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Electronic Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'European Music (Folk  or  Pop)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Hip Hop  or  Rap' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Indie Pop' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Inspirational (incl. Gospel)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Asian Pop (J-Pop, K-pop)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Jazz' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Latin Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'New Age' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Opera' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Pop (Popular music)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'R&B  or  Soul' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Reggae' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Rock' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Singer  or  Songwriter (inc. Folk)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'World Music  or  Beats' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Arts and crafts' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Bicycling' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Camping' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Cooking' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Dancing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Exercise' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Fishing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Gardening' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Hiking' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Karaoke' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Playing an instrument' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Reading' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Scuba diving' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Shopping' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Sightseeing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Singing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Spending time with friends' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Swimming' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Traveling' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Walking' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Watching movies' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Writing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Yoga' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Acro sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Air sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Aquatic & paddle sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Archery' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Ball-over-net games' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Basketball family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Bat-and-ball (safe haven)' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Baton twirling' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Board sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Catch games' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Climbing' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Combat sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Cue sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Cycling' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Equine sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Fantasy sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Fishing' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Flying disc sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Football' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Golf' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Gymnastics' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Handball family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Hockey' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Hunting' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Hurling and shinty' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Ice sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Kindred activities' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Kite sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Lacrosse' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Marker sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Martial Arts' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Mixed discipline' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Motorized sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Musical sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Orienteering family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Other' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Overlapping sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Performance sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Pilota family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Polo' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Racquet (or racket) sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Remote control' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Rodeo-originated' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Running' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Sailing' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Shooting sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Snow sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Stacking' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Street sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Tag games' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Walking' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Weightlifting' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Wrestling' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Action' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Adventure' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Animation' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Biography' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Comedy' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Crime' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Documentary' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Drama' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Family' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Fantasy' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Game-Show' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'History' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Horror' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Music' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Musical' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Mystery' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'News' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Reality-TV' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Romance' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Sci-Fi' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Sitcom' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Sport' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Talk-Show' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Thriller' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'War' );
INSERT INTO Interest_Subcategory VALUES ( 'TV', 'Western' );
