INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Arts and crafts' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Bicycling' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Camping' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Cooking' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Dancing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Exercise' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Fishing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Gardening' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Hiking' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Karaoke' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Playing an instrument' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Reading' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Scuba diving' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Shopping' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Sightseeing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Singing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Spending time with friends' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Swimming' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Traveling' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Walking' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Watching movies' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Writing' );
INSERT INTO Interest_Subcategory VALUES ( 'Recreation', 'Yoga' );
