INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Accounting' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Afrikaans' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Ancient History' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Anthropology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied Art and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied Business' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied ICT' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Applied Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Arabic' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Archaeology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Art and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Bengali' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Biblical Hebrew' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Biology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Business' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Business Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Chemistry' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Chinese' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Citizenship Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Classical Civilisation' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Classical Greek' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Classical Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Communication and Culture' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Computer Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Computing' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Creative Writing' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Critical Thinking' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Dance' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Design and Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Design and Textiles' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Digital Media and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Digital Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Divinity' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Drama' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Drama and Theatre' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Dutch' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Economics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Economics and Business' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Electronics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Engineering' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'English Language' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'English Language and Literature' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'English Literature' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Environmental Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Environmental Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Environmental Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Fashion and Textiles' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Film Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Food Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Food Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'French' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Further Mathematics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'General Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Geography' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Geology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'German' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Global Development' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Global Perspectives and Research' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Government and Politics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Greek' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Gujarati' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Health and Social Care' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Hindi' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Hinduism' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'History' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'History of Art' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Home Economics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Human Biology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Humanities' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'ICT' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Information Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Irish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Islamic Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Italian' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Japanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Journalism' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Latin' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Law' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Leisure Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Life and Health Sciences' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Mathematics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Media Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Modern Hebrew' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Modern Languages' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Moving Image Arts' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Music Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Nutrition and Food Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Panjabi' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Performance Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Performing Arts' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Persian' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Philosophy' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Physical Education' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Physical Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Physics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Polish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Politics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Portuguese' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Product Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Professional Business Services' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Psychology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Pure Mathematics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Quantitative Methods' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Religious Studies' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Russian' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Science in Society' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Sociology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Software Systems Development' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Spanish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Sports Science' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Statistics' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Systems and Control Technology' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Tamil' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Technology and Design' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Thinking Skills' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Travel and Tourism' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Turkish' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Urdu' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'Welsh' );
INSERT INTO Interest_Subcategory VALUES ( 'Academia', 'World Development' );
