INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Absurdist or surreal or whimsical' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Action' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Adventure' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Comedy' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Crime' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Drama' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Fantasy' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Historical' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Historical fiction' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Horror' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Magical realism' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Mystery' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Paranoid' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Philosophical' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Political' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Romance' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Saga' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Satire' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Science fiction' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Slice of Life' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Speculative' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Thriller' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Urban' );
INSERT INTO Interest_Subcategory VALUES ( 'Literature', 'Western' );
