INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Action-adventure' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Adventuring' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Alternate reality' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Arcade' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Board' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Casual' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Computer' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Console' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Conversation' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Cooperative' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Daring' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Dice' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Drinking' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Educational' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Escape' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'First person shooter' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Flash' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Guessing' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Handheld' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Medieval' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Mini' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Mobile' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Multiplayer' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Multiplayer online battle arena' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Narrative' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Party' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Pencil-and-paper' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Platforming' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Pub' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Puzzles' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Real-time strategy' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Role-playing' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Role-playing video' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Skill' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Strategy' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Street' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Tabletop' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Third person shooter' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Video' );
INSERT INTO Interest_Subcategory VALUES ( 'Game', 'Wedding' );
