INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Acro sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Air sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Aquatic & paddle sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Archery' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Ball-over-net games' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Basketball family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Bat-and-ball (safe haven)' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Baton twirling' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Board sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Catch games' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Climbing' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Combat sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Cue sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Cycling' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Equine sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Fantasy sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Fishing' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Flying disc sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Football' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Golf' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Gymnastics' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Handball family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Hockey' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Hunting' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Hurling and shinty' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Ice sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Kindred activities' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Kite sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Lacrosse' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Marker sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Martial Arts' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Mixed discipline' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Motorized sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Musical sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Orienteering family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Other' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Overlapping sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Performance sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Pilota family' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Polo' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Racquet (or racket) sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Remote control' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Rodeo-originated' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Running' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Sailing' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Shooting sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Snow sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Stacking' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Street sports' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Tag games' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Walking' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Weightlifting' );
INSERT INTO Interest_Subcategory VALUES ( 'Sport', 'Wrestling' );
