INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Afghan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'African' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Albanian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'American' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Arabian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Argentinian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Armenian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Asian Fusion' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Australian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Austrian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Bagels' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Bakery' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Bangladeshi' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Barbeque' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Belgian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Brasseries' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Brazilian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Breakfast' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'British' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Brunch' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Buffets' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Burgers' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Burmese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cafes' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cafeteriafood hamburgers' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cajun' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Californian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Calzones' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cambodian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cantonese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Caribbean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Catalan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cheesesteaks' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chicken' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chicken Wings' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chili' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Chinese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Classic' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Coffee and Tea' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Colombian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Comfort Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Costa Rican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Creole' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Crepes' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Cuban' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Czech' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Delis' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Dessertindian food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Dim Sum' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Diner' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Dominican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Eclectic' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ecuadorian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Egyptian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'El Salvadoran' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Empanadas' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'English' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ethiopian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fast Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Filipino' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fine Dining' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fish & Chips' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fondue' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Food Cart' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Food Court' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Food Stands' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'French' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Fresh Fruits' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Frozen Yogurt' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Gastropubs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'German' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Gluten-Free' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Greek' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Grill' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Guatemalan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Gyro' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Haitian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Halalfood korean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hawaiian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Himalayan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hoagies' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hot Dogs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hot Pot' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Hungarian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Iberian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ice Cream' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Indian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Indonesian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Irish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Italian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Jamaican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Japanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Kids' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Korean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Kosher' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Laotian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Late Night' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Latin American' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Lebanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Live or Raw Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Low Carb' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Malaysian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mandarin' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mediterranean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mexican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Middle Eastern' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Modern European' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Mongolian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Moroccan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Nepalese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Noodles' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Nouvelle cuisine' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Nutritious' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Organic' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pakistani' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pancakes' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pasta' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Persian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Persian or Iranian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Peruvian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pitas' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pizza' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Polish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Portuguese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Potato' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Poutineries' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Pub Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Puerto Rican' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ribs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Russian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Salad' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Sandwiches' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Scandinavian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Scottish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Seafood' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Senegalese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Singaporean' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Slovakian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Small Plates' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Smoothies and Juices' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Soul Food' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Soup' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'South African' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'South American' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Southern' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Southwestern' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Spanish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Sri Lankan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Steakhouses' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Subs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Supper Clubs' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Sushi Bars' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Syrian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Szechwan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Taiwanese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Tapas' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Tex-Mex' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Thai' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Tibetan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Turkish' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Ukrainian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Uzbek' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Vegan' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Vegetarian' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Vietnamese' );
INSERT INTO Interest_Subcategory VALUES ( 'Food', 'Wraps' );
