INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Alternative Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Blues' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Classical Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Country Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Dance Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Easy Listening' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Electronic Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'European Music (Folk  or  Pop)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Hip Hop  or  Rap' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Indie Pop' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Inspirational (incl. Gospel)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Asian Pop (J-Pop, K-pop)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Jazz' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Latin Music' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'New Age' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Opera' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Pop (Popular music)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'R&B  or  Soul' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Reggae' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Rock' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'Singer  or  Songwriter (inc. Folk)' );
INSERT INTO Interest_Subcategory VALUES ( 'Music', 'World Music  or  Beats' );
